### ISSUE TITLE
Saves to wrong folder on Android 10

### ISSUE THREAD

**Issue by ataylor32** [rodrigograca31/Canvas2ImagePlugin#4]
Canvas2ImagePlugin.java compares the device's Android version (a string) with the string "2.3.3". On Android 10, this doesn't work as expected. I think the version check should either be updated to work with Android 10 or it should be removed entirely (I doubt there are many users still on Android 2 at this point).

**Comment by rodrigograca31** [comment]
I totally agree! Saw that years ago.
I personally only support 4.4+ and even 4.4 Kitkat is dying....

**Comment by rodrigograca31** [comment]
What's the normal output of `deviceVersion.compareTo("2.3.3");` ???
and what does Android 10 outputs?

**Comment by ataylor32** [comment]
I don't know what the normal output is, but on Android 10, `check` has a value of `-1`

**Comment by rodrigograca31** [comment]
Ok, give me 10 minutes to change it and commit a new minor version.
or you want to do a PR?

**Comment by ataylor32** [comment]
I can give it a try.

**Comment by rodrigograca31** [comment]
ok. go ahead.

**Comment by ataylor32** [comment]
Fixed by #6
