### ISSUE TITLE
Save as JPEG instead of PNG

### ISSUE THREAD

**Issue by ataylor32** [rodrigograca31/Canvas2ImagePlugin#5]
It looks like this issue was never resolved:

https://github.com/devgeeks/Canvas2ImagePlugin/issues/12

I'm working on an app that would benefit from this.

**Comment by rodrigograca31** [comment]
:thinking:

**Comment by rodrigograca31** [comment]
I have a big app that uses this plugin.... Every now and then some users complain about image quality..... I think JPEG is more compressed thus should have less quality but this might be problem they are having..... (PNG)

**Comment by rodrigograca31** [comment]
I'm performing some tests and the results are promising.

Saving 3 images. First 3 lines are milliseconds taken to save in `jpeg` and next 3 are milliseconds taken to save in `png` like now.
![image](https://user-images.githubusercontent.com/1134310/65273290-b68e7c00-db18-11e9-90a7-458fa9b8dac3.png)

**Comment by rodrigograca31** [comment]
It's almost implemented. Will finish tomorrow night and test and commit....

**Comment by rodrigograca31** [comment]
@ataylor32 please test it and give me some feedback if everything is ok.

**Comment by ataylor32** [comment]
I haven't tested on iOS yet, but I tested on Android and it worked fine. Thank you very much!

**Comment by rodrigograca31** [comment]
ooooooooooops!

I totally forgot about iOS.....
I don't know Swift or whatever so.........

Probably better to reopen this issue and tag it as "iOS help needed"

Thoughts?

**Comment by ataylor32** [comment]
I believe it's actually Objective-C. I'm not familiar with it myself, but I looked at the code. There's significantly less code compared to Android. I didn't see anything about image format, so maybe it detects the format with magic and does the right thing. So maybe it will just work. I'll test it at some point and let you know how it goes.

**Comment by rodrigograca31** [comment]
Yeah, Objective-C. 

Yeah it should just work.... Unless me passing an extra argument messes with something....

P.S. @ataylor32 would you mind staring this repo? Thanks.

**Comment by ataylor32** [comment]
Starred

**Comment by rodrigograca31** [comment]
Thanks. It's so that this repo gets more visibility.
I was even thinking making it a stand alone repo instead of a fork and renaming the plugin and publishing to npm....

**Comment by ataylor32** [comment]
I was able to test on iOS today and both image formats work just fine.

**Comment by rodrigograca31** [comment]
:+1: yeah, it doesnt have effect.... it will save in whatever format iOS saves....
